name: Purge untagged images

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package
# Run cleanup job if a new package was published or updated
on:
  registry_package:

jobs:
  purge_untagged_images:
    runs-on: ubuntu-latest
    steps:
      - name: clean packages
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GHCR_TOKEN}}
          organization: ${{ github.repository_owner}}
          container: ${{ secrets.GHCR_IMAGE_NAME }}
          untagged: true